### ISSUE TITLE
SglPPow package as suggested for SmallGrp?

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/smallgrp#11]
Should SglPPow (https://www.gap-system.org/Packages/sglppow.html) be specified in PackageInfo.g as suggested package?

For example, if it is loaded, SglPPow works for some more orders.

**Comment by markuspf** [comment]
Maybe you could provide a pull-request that does that?

**Comment by fingolfin** [comment]
This issue asks a question, but completely fails to give any motivation for this -- so, I'd say "NO! Unless you can give arguments why it should do so"

**Comment by alex-konovalov** [comment]
"If it is loaded, SglPPow works for some more orders" is already a motivation. In a few more words, the behaviour of `NrSmallGroups`, `AllSmallGroups` etc. depends on whether `SglPPow` is loaded or not, and that may come as a surprise to an unsuspecting user. Further discussion is in the PR implementing this - please see #14.

**Comment by fingolfin** [comment]
I completely disagree that this is a justification for loading sglppow by default. In the future, we will add more extensions to the library of small groups, in separate packages. It doesn't make sense to have them all autoload. Indeed, isn't the long term to not even autoload `smallgrp` itself?

**Comment by alex-konovalov** [comment]
I think this is purely a question of sorting out package dependencies, so the intention to not even autoload smallgrp itself is secondary here. In this case the whole bunch of packages will not be loaded, and that's fine with me.

We define that package B is suggested for A is "B is not essential for A but should be loaded if it is available (for example because B provides some improvements of the main system that are useful for A)". 

This is the case here. When the package is loaded, `SmallGroup`, `NumberSmallGroups` and `SmallGroupsInformation` are covering further orders. 

I think that GAP users are used to the fact that the GAP small group library is always available in GAP. They may also know that for some orders above 2000 there are collections of groups too (although time to time I hear claims about 2000 as upper limit). So one could be used to asking `NrSmallGroups` etc. to decide whether groups of a given order are available or not. 

Hence I do think that the SmallGrp package should have SglPPow as suggested. If there are still objections, it should definitely write in README and some visible place in the manual that the user may be interested to use SglPPow as well.

**Comment by fingolfin** [comment]
The sglppow only exists for a relatively short time, so I don't agree that people will "expect" it to be present. And if I release a package in a few weeks which extends `NumberSmallGroups` to order up to 20000, people *definitely* will not "expect" it to be present. 

I am also quite suprised to hear you argue in this direction in view of https://github.com/gap-system/gap/pull/1135 -- there, you seem to work in the opposite direction: removing packages that people "expect" to be present, and whose absence will mean functionality that previously was "just there" won't be, and things which were fast will be slower, etc.

**Comment by fingolfin** [comment]
Let me clarify what I want: I don't want sglppow to be auto loaded. I am fine if people are told in some way that it might be useful (in the README; in the form of info messages; or some other means). But I am very unhappy about adding three packages (sglppow, liering, liepring) to the list of packages loaded into every GAP session in a default GAP installation, for IMHO no good reason at all.

**Comment by alex-konovalov** [comment]
@fingolfin first, I never said that people will expect *sglppow* to be present! To the contrary, I suspect that many people didn't know about it yet. 

My actual point was that the surprise factor for a user will be that there are collections of groups or small orders that are NOT automatically present. Because usually one just asks AllSmallGroups without loading any additional components. 

Also, I consider that this leads to more packages will be loaded in a default GAP installation as a side effect of package dependencies for SmallGrp. So it's not directly contradicting to the direction of movement in #1135 (which however raised quite diverse responses). If SmallGrp would be taken out from default session, those three packages would not be loaded too.

The idea of Info messages seems to be most suitable for the purpose. One could modify functions to produce info messages when requested order is p^7 for p>11 or 3^8 and recommend to load SglPPow. I think this will completely cover the needs of informing the user about SglPPow without expanding dependencies. I will try to submit a pull request. Put a reminder in #22.

**Comment by alex-konovalov** [comment]
Maybe i was unclear in the last comment. My point was that currently in GAP 4.8 a user may be surprised that there are collections of groups or small orders that are NOT automatically present. Using dependencies specified in PackageInfo.g we may be able to improved that by loading SglPPow as suggested package. But if instead of doing that, we will be able to produce and info message, I find it quite suitable.
