### ISSUE TITLE
Add `SmallGroupsAvailable`, `NumerSmallGroupsAvailable`, `IdGroupsAvailable`

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/smallgrp#20]
The `transgrp` and `primgrp` packages offer user functions `PrimitiveGroupsAvailable` and `TransitiveGroupsAvailable` to make it possible to query what data is available. It would be nice if `smallgrp` offered something similar.

Of course there are `SMALL_AVAILABLE` and `ID_AVAILABLE`, but they are undocumented internal functions, and as such their interface is not really straight-forward or user friendly. I suggest adding these:
* `SmallGroupsAvailable(order)` returning true/false if a list of all small groups of that order is available
* `NumberSmallGroupsAvailable(order)` --  almost the same, but returns `true` for 1024.
* `IdGroupsAvailable(order)`

All of them should be straight forward to implement using `{SMALL,ID}_AVAILABLE`. I'd whip up a patch, but then you'd rightfully ask for tests etc.... anyway, didn't want this to be lost.

Of course we then could wonder whether to add them to GAP, too, for the transition, similar to what was done for `transgrp` and `primgrp`. But perhaps that is simply not necessary, as nothing in the library needs this right now, I think...

**Comment by cdwensley** [comment]
I've started using "if not ( SMALL_AVAILABLE( n ) = fail ) then ...  IdGroup(n,k) ..." in XMod, so will be glad when IdGroupsAvailable becomes available.
