### ISSUE TITLE
Canonical name of the package: SmallGrp or smallgrp

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/smallgrp#21]
I suggest to use mixed case: SmallGrp. If there are no objections, I will make a PR.

**Comment by alex-konovalov** [comment]
See also discussion whether to use TransGrp or transgrp in https://github.com/hulpke/transgrp/issues/19

**Comment by markuspf** [comment]
I don't mind which name the package has, but I'll not start renaming things myself (i.e. I'll merge pull requests that address this problem, but not do all the renaming myself).

**Comment by alex-konovalov** [comment]
OK, let me first try TransGrp, if that will work, I will make PR here too :)
