### ISSUE TITLE
Document NrSmallGroups

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/smallgrp#25]
`NrSmallGroups` is a synonym of `NumberSmallGroups` but is not documented.

Extracted from https://github.com/gap-system/gap/issues/407

**Comment by fingolfin** [comment]
Actually many (all?) other synonyms provided by this package are also not documented, such as `AllGroups`, `OneGroup`, `IdsOfAllGroups`, ...

**Comment by fingolfin** [comment]
They are, however, mentioned in the README.

**Comment by fingolfin** [comment]
Fixed by 36a0d298df7540589703a57e894ece1fc84add75
