### ISSUE TITLE
Permutation for orders 3^7,5^7, 7^7, 11^7  are wrongly documented and implemented

### ISSUE THREAD

**Issue by hulpke** [gap-packages/smallgrp#38]
There was a renumbering of small groups of order 5^7, 7^7, 11^7. Bettina Eick sent me e.g. the following permutation for 5^7 that corrects the numbering to be compatible with Magma:

        perm5  := [1];
    Append(perm5, [ 30083, 30084, 30085, 30086 ]);
    Append(perm5, [2..30082]);

In `small.gd` this permutation exist in comments, but then in `SMALL_GROUPS_PERM5` a different permutation is built up. Also the documentation and tests claim the permutation is an involution, which is not true.

This was put in wrongly in 
https://github.com/gap-packages/smallgrp/commit/b44d82400c3b835b8b2056bfc250aa4a76a15e2f

(Similar errors are in order 7^7 and 11^7)

As a result, the numbering used by GAP is  different than in Magma, Viz (from Mark Lewis):

    In Magma:  g := SmallGroup (5^7, 348);

    yielded:  Exponent (g);
                 125
                 DerivedLength (g);
                 2

    In GAP:  g := SmallGroup (5^7,348);
               Exponent (g);
               25
               DerivedLength (g);
               3

This discrepancy needs to be documented and fixed. Given that users consider it as the GAP library this should be part of changes in a release.

**Comment by hulpke** [comment]
I have now compared the groups for exponent p^7, 3<=p<=11 explicitly between GAP and MAGMA and there are sighnificant discrepancies beyond the assumed simple shift. 
I will prepare a PR that provides permutations that I checked.

**Comment by hulpke** [comment]
@markuspf Comparing with Magma, the changes turn out to be more than the easy shifts, I thus submitted a PR of my own.

**Comment by alex-konovalov** [comment]
@hulpke the fix should perhaps be mentioned in the release notes for GAP 4.11 under "packages"? If so, could you provide a description please?

**Comment by hulpke** [comment]
@alex-konovalov 
Release notes: 
The arrangement of small groups in degrees p^7, p=3,5,7,11, has been corrected.

Once anyone lets me know that a new version has been wrapped and is available for download I will write a mail to the forum, explaining details.

**Comment by alex-konovalov** [comment]
Thanks @hulpke. Shall we add "to ensure that their numbering is the same in GAP and Magma"?
