### ISSUE TITLE
Update author details

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/smallgrp#51]
@beick has a new URL for her homepage: need to change www.icm.tu-bs.de/~beick to www.iaa.tu-bs.de/beick here and in all other packages (which are now on GitHUb, except NilMat).

**Comment by alex-konovalov** [comment]
Nilmat is now at https://github.com/gap-packages/nilmat

**Comment by fingolfin** [comment]
Finished in f6d8a9cbb928a63120e80d82525af1c078984881
