### ISSUE TITLE
SmallGroupsInformation(512)

### ISSUE THREAD

**Issue by davidburrell** [gap-packages/smallgrp#58]
The p-class of the groups of order 512 with ids [445..858] are listed incorrectly via SmallGroupsInformation(512) as having p-class 5, but if you check they all have p-class 4.

Here is a working example to reproduce:
```
Collected(List([445..858],x->PClassPGroup(SmallGroup(512,x))));
[ [ 4, 414 ] ]
```

**Comment by fingolfin** [comment]
@davidburrell did you check all groups of order 512 if there are more issues of the same kind? I just started a run to see that, but in case you already did it...

So far my program is at this point (it iterates over all the groups in sequence and tries to find ranges with equal `[rank, p-class]` pairing, and prints those ranges). I'll update this list on occassion as my code progresses.
```
[ 1, 9 ] at 1 - 1
[ 2, 3 ] at 2 - 10
[ 2, 4 ] at 11 - 386
[ 2, 5 ] at 387 - 444   # <-
[ 2, 4 ] at 445 - 858   # <- the "nonlinearity pointed out here
[ 2, 5 ] at 859 - 1698  # <-
[ 2, 6 ] at 1699 - 2008
[ 2, 7 ] at 2009 - 2039
[ 2, 8 ] at 2040 - 2044
[ 3, 2 ] at 2045 - 2045
[ 3, 3 ] at 2046 - 29398
[ 3, 4 ] at 29399 - 30617 # <-
[ 3, 3 ] at 30618 - 31239 # <- another non-linearity, but documented
[ 3, 4 ] at 31240 - 56685 # <-
[ 3, 5 ] at 56686 - 60615
[ 3, 6 ] at 60616 - 60894
[ 3, 7 ] at 60895 - 60903
[ 4, 2 ] at 60904 - 67612
```

**Comment by davidburrell** [comment]
I did run a check here are the results

#512
#Groups 1-1 have rank 1 and p-class 9
#Groups 2-10 have rank 2 and p-class 3

#Groups 11-386 have rank 2 and p-class 4
#Groups 387-444 have rank 2 and p-class 5
#Groups 445-858 have rank 2 and p-class 4
#Groups 859-1698 have rank 2 and p-class 5

#Groups 1699-2008 have rank 2 and p-class 6
#Groups 2009-2039 have rank 2 and p-class 7
#Groups 2040-2044 have rank 2 and p-class 8
#Groups 2045-2045 have rank 3 and p-class 2

#Groups 2046-29398 have rank 3 and p-class 3
#Groups 29399-30617 have rank 3 and p-class 4
#Groups 30618-31239 have rank 3 and p-class 3
#Groups 31240-56685 have rank 3 and p-class 4

#Groups 56686-60615 have rank 3 and p-class 5
#Groups 60616-60894 have rank 3 and p-class 6
#Groups 60895-60903 have rank 3 and p-class 7
#Groups 60904-67612 have rank 4 and p-class 2
#Groups 67613-387088 have rank 4 and p-class 3
#Groups 387089-419734 have rank 4 and p-class 4
#Groups 419735-420500 have rank 4 and p-class 5
#Groups 420501-420514 have rank 4 and p-class 6
#Groups 420515-6249623 have rank 5 and p-class 2
#Groups 6249624-7529606 have rank 5 and p-class 3
#Groups 7529607-7532374 have rank 5 and p-class 4
#Groups 7532375-7532392 have rank 5 and p-class 5
#Groups 7532393-10481221 have rank 6 and p-class 2
#Groups 10481222-10493038 have rank 6 and p-class 3
#Groups 10493039-10493061 have rank 6 and p-class 4
#Groups 10493062-10494173 have rank 7 and p-class 2
#Groups 10494174-10494200 have rank 7 and p-class 3
#Groups 10494201-10494212 have rank 8 and p-class 2
#Groups 10494213-10494213 have rank 9 and p-class 1

**Comment by fingolfin** [comment]
As it seems the actual data in the library is correct, just the sorting is unfortunately not as nice as it should be, I've made PR #60 to adjust the output of `SmallGroupsInformation(512)` to match reality.
