### ISSUE TITLE
Make LICENSE clear

### ISSUE THREAD

**Issue by markuspf** [gap-packages/smallgrp#7]

**Comment by fingolfin** [comment]
IIRC the plan was to use https://opensource.org/licenses/Artistic-2.0, correct?

**Comment by markuspf** [comment]
I emailed the authors to confirm that this license is the one they wish to use for this library.

**Comment by markuspf** [comment]
I got confirmation from Bettina Eick that the artistic license is the one to go for, so I added it to the repository.
